### ISSUE TITLE
BMP trace causes assertion failure in unicast-path-preference

### ISSUE THREAD

**Issue by agember** [ahorn/nopticon#10]
Running with `--verbosity 0 --reach-summary 1576.0` and [this BMP log](https://github.com/ahorn/nopticon/files/2621122/bmp_end.txt) results in the error:
`gobgp-analysis: src/analysis.cc:538: nopticon::timestamps_t nopticon::intersect(const timestamps_t&, const timestamps_t&): Assertion `std::is_sorted(a.begin(), a.end())' failed.`

**Comment by ahorn** [comment]
Sorry, I know it's easy to forget but I need the rDNS file, too.

**Comment by agember** [comment]
Sorry, here's the [rDNS file](https://github.com/ahorn/nopticon/files/2624112/rdns.txt).

**Comment by ahorn** [comment]
@agember I reproduced the issue with a small test case and fixed it. Please close the issue if you are happy with the fix.
