### ISSUE TITLE
BMP trace causes duration assertion failure

### ISSUE THREAD

**Issue by agember** [ahorn/nopticon#11]
After commit 11b67292, running nopticon with `--verbosity 0 --reach-summary 1226.0` and [this BMP trace](https://github.com/ahorn/nopticon/files/2621817/bmp_peerchange.txt) (which includes refresh commands) causes the following assertion failure:
```gobgp-analysis: src/analysis.cc:42: nopticon::rank_t nopticon::history_t::rank(const nopticon::slice_t&, nopticon::timestamp_t, nopticon::timestamp_t) const: Assertion `duration <= global_stop - global_start' failed.```

It's not clear to me what this assertion is checking and why it is failing.

**Comment by ahorn** [comment]
I forgot to cherry-pick commit a9e675cec42ab8b92fae88004e1b6eb88af11577 and merge it back into master. This is done now.

**Comment by agember** [comment]
Thanks, this fixes the problem.
